from fusionglpi import db

class Infocom(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    entity_id = db.Column(db.Integer, db.ForeignKey('entity.id'))
    is_recursive = db.Column(db.Boolean, nullable=False, server_default="0")
    item_type = db.Column(db.String(100, None, True))
    item_id = db.Column(db.Integer, nullable=False, server_default="0")
    comment = db.Column(db.Text)
    buy_date = db.Column(db.Date)
    use_date = db.Column(db.Date)
    order_date = db.Column(db.Date)
    delivery_date = db.Column(db.Date)
    inventory_date = db.Column(db.Date)
    warranty_date = db.Column(db.Date)
    warranty_duration = db.Column(db.Integer, nullable=False, server_default="0")
    warranty_info = db.Column(db.String(255, None, True))
    supplier_id = db.Column(db.Integer, db.ForeignKey('supplier.id'))
    order_number = db.Column(db.String(255, None, True))
    delivery_number = db.Column(db.String(255, None, True))
    immo_number = db.Column(db.String(255, None, True))
    value = db.Column(db.Float)
    warranty_value = db.Column(db.Float)
    sink_time = db.Column(db.Integer, nullable=False, server_default="0")
    sink_type = db.Column(db.Integer, nullable=False, server_default="0")
    sink_coeff = db.Column(db.Float)
    bill = db.Column(db.String(255, None, True))
    budget_id = db.Column(db.Integer, db.ForeignKey('budget.id'))
    alert = db.Column(db.Integer, nullable=False, server_default="0")
