from fusionglpi import db

class Ipnetwork(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    entity_id = db.Column(db.Integer, db.ForeignKey('entity.id'))
    is_recursive = db.Column(db.Boolean, nullable=False, server_default="0")
    name = db.Column(db.String(255, None, True))
    comment = db.Column(db.Text)
    completename = db.Column(db.Text)
    level = db.Column(db.Integer, nullable=False, server_default="0")
    ancestors_cache = db.Column(db.Text)
    descendants_cache = db.Column(db.Text)
    addressable = db.Column(db.Boolean, nullable=False, server_default="0")
    version = db.Column(db.Integer, nullable=False, server_default="0")
    address = db.Column(db.String(255, None, True))
    address_0 = db.Column(db.Integer, nullable=False, server_default="0")
    address_1 = db.Column(db.Integer, nullable=False, server_default="0")
    address_2 = db.Column(db.Integer, nullable=False, server_default="0")
    address_3 = db.Column(db.Integer, nullable=False, server_default="0")
    netmask = db.Column(db.String(255, None, True))
    netmask_0 = db.Column(db.Integer, nullable=False, server_default="0")
    netmask_1 = db.Column(db.Integer, nullable=False, server_default="0")
    netmask_2 = db.Column(db.Integer, nullable=False, server_default="0")
    netmask_3 = db.Column(db.Integer, nullable=False, server_default="0")
    gateway = db.Column(db.String(255, None, True))
    gateway_0 = db.Column(db.Integer, nullable=False, server_default="0")
    gateway_1 = db.Column(db.Integer, nullable=False, server_default="0")
    gateway_2 = db.Column(db.Integer, nullable=False, server_default="0")
    gateway_3 = db.Column(db.Integer, nullable=False, server_default="0")
    